In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pandas.core.algorithms import duplicated

In [3]:
df=pd.read_csv("telecom_data.csv")
df.head()

,Transaction_ID,Date,Product_Category,Price,Customer_Satisfaction
0,TXN1057,7/20/2026,Network_Service,44.982481,2.0
1,TXN1039,2/10/2026,Data_Plan,33.833828,1.0
2,TXN1321,11/21/2026,Network_Service,37.535748,5.0
3,TXN1281,6/6/2026,Support_Ticket,41.362726,3.0
4,TXN1280,7/4/2026,Support_Ticket,42.042483,2.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Transaction_ID         510 non-null    object
 1   Date                   510 non-null    object
 2   Product_Category       510 non-null    object
 3   Price                  485 non-null    float64
 4   Customer_Satisfaction  483 non-null    float64
dtypes: float64(2), object(3)
memory usage: 20.1+ KB

In [7]:
df.isna().sum()

Transaction_ID            0
Date                      0
Product_Category          0
Price                    25
Customer_Satisfaction    27
dtype: int64

In [9]:
df.describe()

             Price  Customer_Satisfaction
count   485.000000             483.000000
mean    100.958452               3.004141
std     500.752903               1.431704
min       1.380990               1.000000
25%      40.060644               2.000000
50%      49.816298               3.000000
75%      60.193966               4.000000
max    5000.000000               5.000000

In [12]:
(df["Price"]==0).sum()

np.int64(0)

In [13]:
(df["Customer_Satisfaction"]==0).sum()

np.int64(0)

In [14]:
df.duplicated().sum()

np.int64(10)

In [25]:
df[df.duplicated(subset="Transaction_ID" ,keep=False)]

,Transaction_ID,Date,Product_Category,Price,Customer_Satisfaction
12,TXN1361,7/11/2026,Network_Service,40.940222,4.0
22,TXN1471,4/17/2026,Support_Ticket,47.834594,4.0
58,TXN1131,1/8/2026,Network_Service,48.047854,NaN
86,TXN1410,4/11/2026,Data_Plan,43.335601,NaN
123,TXN1129,11/28/2026,Support_Ticket,45.345999,2.0
163,TXN1361,7/11/2026,Network_Service,40.940222,4.0
203,TXN1170,3/8/2026,Support_Ticket,54.840778,5.0
261,TXN1036,11/16/2026,Support_Ticket,42.921022,1.0
315,TXN1131,1/8/2026,Network_Service,48.047854,NaN
326,TXN1455,9/28/2026,Data_Plan,27.452856,3.0
343,TXN1330,1/11/2026,Network_Service,51.489985,2.0
354,TXN1410,4/11/2026,Data_Plan,43.335601,NaN
394,TXN1170,3/8/2026,Support_Ticket,54.840778,5.0
431,TXN1330,1/11/2026,Network_Service,51.489985,2.0
432,TXN1479,9/13/2026,Support_Ticket,72.559895,4.0
476,TXN1479,9/13/2026,Support_Ticket,72.559895,4.0
480,TXN1455,9/28/2026,Data_Plan,27.452856,3.0
497,TXN1129,11/28/2026,Support_Ticket,45.345999,2.0
503,TXN1471,4/17/2026,Support_Ticket,47.834594,4.0
507,TXN1036,11/16/2026,Support_Ticket,42.921022,1.0

In [26]:
df[df.duplicated()]

,Transaction_ID,Date,Product_Category,Price,Customer_Satisfaction
163,TXN1361,7/11/2026,Network_Service,40.940222,4.0
315,TXN1131,1/8/2026,Network_Service,48.047854,NaN
354,TXN1410,4/11/2026,Data_Plan,43.335601,NaN
394,TXN1170,3/8/2026,Support_Ticket,54.840778,5.0
431,TXN1330,1/11/2026,Network_Service,51.489985,2.0
476,TXN1479,9/13/2026,Support_Ticket,72.559895,4.0
480,TXN1455,9/28/2026,Data_Plan,27.452856,3.0
497,TXN1129,11/28/2026,Support_Ticket,45.345999,2.0
503,TXN1471,4/17/2026,Support_Ticket,47.834594,4.0
507,TXN1036,11/16/2026,Support_Ticket,42.921022,1.0

In [27]:
df=df.drop_duplicates()

In [28]:
df

,Transaction_ID,Date,Product_Category,Price,Customer_Satisfaction
0,TXN1057,7/20/2026,Network_Service,44.982481,2.0
1,TXN1039,2/10/2026,Data_Plan,33.833828,1.0
2,TXN1321,11/21/2026,Network_Service,37.535748,5.0
3,TXN1281,6/6/2026,Support_Ticket,41.362726,3.0
4,TXN1280,7/4/2026,Support_Ticket,42.042483,2.0
...,...,...,...,...,...
504,TXN1016,9/16/2026,Support_Ticket,NaN,2.0
505,TXN1040,8/22/2026,Data_Plan,39.270444,2.0
506,TXN1304,2/2/2026,Hardware,51.160525,4.0
508,TXN1343,6/28/2026,Hardware,25.077199,5.0
509,TXN1264,6/14/2026,Data_Plan,35.214109,1.0